docker-build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - ''
    - tag=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:${tag}"
      .
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:${tag}"
    - docker system prune -a
  rules:
    - if: "$CI_COMMIT_BRANCH"
      exists:
        - Dockerfile
